### ISSUE TITLE
Scoring on (epi)weekly scale

### ISSUE THREAD

**Issue by SamuelBrand1** [CDCgov/pyrenew-hew#110]
At the moment scoring (on the scoring branch) is done daily, and averaged over a week.

This could be useful to keep this, but noting that this includes scoring within-week effects, but we should also have weekly aggregated then scored utility.

### Sub-task planning

- [x] Land #148 
- [x] Add generate epiweekly truth data from daily truth data step
- [x] Add run baseline models on epiweekly
- [x] Add extra pyrenew-hew postprocess to chunk the daily posterior preds into epiweekly
- [x] check how much revision the scoring function needs (might be zero)

**Comment by SamuelBrand1** [comment]
Connected to #79

**Comment by SamuelBrand1** [comment]
A wrinkle here is that there are more than one ways to add to the code base in order to do this:

1. Add functionality so that all forecast models that currently forecast daily scale have an optional step to collate into weekly scale. The downside here is that the cdc baseline forecaster needs to be averaged (only the % forecasts are available which can't be used to calculate the actual weekly % due to missing actual denominator).
2. Add functionality so that the `pyrenew` forecaster has weekly binning, and that the forecasts of the other models are based on ingesting only weekly data.

The main difference between 1/2 is that the baseline models are then aimed at being optimised for scoring on weekly scale. The belief is that the semi-mechanistic `pyrenew` model will forecast best based on daily inference, _even if the target is weekly_. This seems reasonable, and the daily scale of dynamics is important for the modelling, but is currently untested.

**Comment by SamuelBrand1** [comment]
Blocked by #148 , but when resolved this will be in a good place to resolve.

**Comment by SamuelBrand1** [comment]
#148 got done so this is ready for closing by #159 .
